global :
  scrape_interval : 3s
  evaluation_interval : 3s

scrape_configs :
   - job_name : 'poem-monitoring'
     metrics_path : '/actuator/prometheus'
     static_configs :
       - targets : ['poem-application:8080']
